FROM alpine:latest

RUN apk update && apk upgrade --no-cache && \
    apk add --no-cache imagemagick ghostscript ffmpeg && \
    fc-cache -f

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
